name: get proxy

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Pull files
        run: |
          git config --local user.email "rbellaputri12@gmail.com"
          git config --local user.name "FifzzSENZE"
          git pull origin master
      
      - name: Get proxies
        run: |
          python main.py

      - name: Commit files
        run: |
          git add proxies/
          git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)" -a
          git branch -u origin/master
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_PAT }}
          branch: master 
